import type { Choice, Episode, Scene, ShotSpec } from '@/types'

/* ============================================================================
 * EPISODE 01 — "FIRST DAY"
 *
 * Authored as a graph of data. The runtime walks it deterministically:
 * scene -> (choice) -> consequence -> next. No LLM is consulted to decide
 * what happens. LLMs are used for (a) generating graphs like this one from
 * company material at authoring time, and (b) in-character conversation.
 *
 * `shot` is the shot specification: the prompt the Studio hands to a video or
 * image provider (src/media). Generated files attach as `Scene.assets`; the
 * player never waits for one, and without them the procedural renderer draws
 * the shot. `threat` tags each decision's risk shape for run telemetry.
 * ========================================================================== */

const shot = (
  env: ShotSpec['env'],
  time: ShotSpec['time'],
  mood: ShotSpec['mood'],
  prompt: string,
): ShotSpec => ({ env, time, mood, prompt })

/** Compact builder for consequence scenes. */
const consequence = (
  id: string,
  act: number,
  s: ShotSpec,
  tone: 'good' | 'bad' | 'mixed',
  banner: string,
  dialogue: Scene['dialogue'],
  lesson: string,
  citations: string[],
  next: string,
  chatWith: string[],
  chatHook: string,
): Scene => ({
  id,
  kind: 'consequence',
  act,
  shot: s,
  dialogue,
  outcome: { tone, banner, lesson, citations },
  next,
  chatWith,
  chatHook,
})

const choice = (c: Choice): Choice => c

/* -------------------------------------------------------------------------- */
/* ACT 1 — THE INBOX                                                           */
/* -------------------------------------------------------------------------- */

const act1: Scene[] = [
  {
    id: 's1_arrival',
    kind: 'cinematic',
    act: 1,
    title: 'HELIX DYNAMICS',
    subtitle: 'MONDAY · 08:52 · GROUND FLOOR',
    shot: shot(
      'lobby',
      'morning',
      'warm',
      'Wide low-angle shot, glass atrium lobby of a modern tech company at 8:52am. Cold morning light through tall windows, long shadows across polished concrete. A new employee in a slightly-too-new jacket crosses frame holding a visitor badge. Shallow depth of field, anamorphic flare, 35mm, muted teal and amber grade.',
    ),
    dialogue: [
      { characterId: 'you', line: 'Day one. Badge works. That is one thing that went right.', direction: 'The lobby doors seal behind you with a soft pneumatic sigh.' },
      { characterId: 'morty', line: "You're the new associate, right? I'm Morty. I started Thursday, so I'm basically staff now.", direction: 'He is holding two coffees and clearly does not want either of them.' },
      { characterId: 'morty', line: "I'll walk you up. Fair warning — the fourth floor is a lot." },
    ],
    next: 's1_desk',
  },
  {
    id: 's1_desk',
    kind: 'cinematic',
    act: 1,
    title: 'FLOOR FOUR',
    subtitle: '09:14 · YOUR DESK',
    shot: shot(
      'desk',
      'morning',
      'neutral',
      'Medium close shot over the shoulder of a laptop on a clean desk, open-plan office softly out of focus behind. Screen glow on the face. A notification slides into frame. Handheld micro-movement, 50mm, natural window light.',
    ),
    dialogue: [
      { characterId: 'you', line: 'Laptop. Badge. A mug with someone else’s name on it. You are officially employed.' },
      { characterId: 'morty', line: 'Hey — I just got this weird email from IT. It says we need to verify our account immediately or it gets suspended at noon.', direction: 'He turns his screen towards you. The logo looks right. The urgency does not.' },
      { characterId: 'rick', line: "Just click it. It's fine. IT sends that thing every quarter and it's always fine.", direction: 'Rick has not looked up from his own screen once.' },
      { characterId: 'morty', line: "It... says noon though. Would IT really give us a deadline? Wait — you got it too. It's in your inbox." },
    ],
    next: 'd1_email',
  },
  {
    id: 'd1_email',
    kind: 'decision',
    act: 1,
    title: 'THE SUSPICIOUS EMAIL',
    threat: { source: 'external', pressure: 'urgency' },
    shot: shot(
      'desk',
      'morning',
      'tense',
      'Tight insert shot of an email client on screen: sender "IT Service Desk", subject "ACTION REQUIRED: verify your account before 12:00". Cursor hovering over a blue link. Screen light flickering on a face just out of focus. High contrast, shallow focus.',
    ),
    dialogue: [{ characterId: 'rick', line: 'Clock’s ticking, rookie.', direction: 'He is enjoying this slightly too much.' }],
    prompt: 'WHAT DO YOU DO?',
    allowWager: true,
    choices: [
      choice({
        id: 'd1_a',
        label: 'A',
        text: 'Click the link and see whether the page looks real.',
        consequenceSceneId: 'c1_click',
        knowledgeConcepts: ['phishing', 'password_security'],
        scoreImpact: -12,
        quality: 'poor',
        ledgerLabel: 'Clicked an unverified link',
      }),
      choice({
        id: 'd1_b',
        label: 'B',
        text: 'Report it with the Report Phish button and tell Morty not to touch it.',
        consequenceSceneId: 'c1_report',
        knowledgeConcepts: ['phishing', 'incident_reporting'],
        scoreImpact: 14,
        quality: 'best',
        ledgerLabel: 'Identified and reported phishing attempt',
      }),
      choice({
        id: 'd1_c',
        label: 'C',
        text: 'Reply to the email and ask IT to confirm it is genuine.',
        consequenceSceneId: 'c1_reply',
        knowledgeConcepts: ['phishing', 'social_engineering'],
        scoreImpact: -2,
        quality: 'acceptable',
        ledgerLabel: 'Verified — through the attacker’s channel',
      }),
    ],
  },
  consequence(
    'c1_click',
    1,
    shot(
      'desk',
      'morning',
      'alarm',
      'Handheld shot pushing in on a laptop screen: a pixel-perfect clone of a corporate SSO login page. Cut to the screen dimming, then a cascade of permission dialogs. Reflection of a worried face in the dark part of the screen. Cold blue light, rising unease.',
    ),
    'bad',
    'SECURITY INCIDENT',
    [
      { characterId: 'you', line: 'The login page loads. It looks exactly right. You are halfway through typing before you stop.', direction: 'The URL reads helix-verify-sso.co. Not helix.internal.' },
      { characterId: 'morty', line: "Wait. Wait — your screen just... did something. Did it do that? Mine didn't do that.", direction: 'Two browser windows you did not open blink into existence.' },
      { characterId: 'rick', line: 'Huh. That’s new.', direction: 'For the first time all morning, Rick is looking at your screen.' },
      { characterId: 'summer', line: 'This is Summer from Security. Your session flagged a credential-harvesting domain ninety seconds ago. Unplug the network cable and leave everything exactly as it is. You are not in trouble.', direction: 'She is already at the end of the row.' },
    ],
    'The page was a clone. Real credentials typed into a fake login are captured live — including the MFA code, which an attacker can replay within seconds. The handbook is blunt about why: Helix IT never asks you to verify your account through a link. The domain was the only tell, and you only get to check it before you click.',
    ['K-PHI-01', 'K-PHI-03', 'K-INC-02'],
    's2_intro',
    ['summer', 'morty'],
    'Summer is at your desk and she is not angry. Ask her anything.',
  ),
  consequence(
    'c1_report',
    1,
    shot(
      'desk',
      'morning',
      'calm',
      'Clean insert of a "Report Phish" button being clicked, confirmation toast sliding in. Cut wide: the open-plan floor, a security advisory filling a large wall monitor. Warm light returning. Composed, steady camera.',
    ),
    'good',
    'THREAT CONTAINED',
    [
      { characterId: 'you', line: 'One button. The message greys out and disappears into the void.' },
      { characterId: 'summer', line: 'Security. Your report came in at 09:21 — first one. The domain was registered eleven hours ago and it is a credential harvester. We have blocked it company-wide.', direction: 'A banner goes up on the floor monitor: ACTIVE PHISHING CAMPAIGN — DO NOT INTERACT.' },
      { characterId: 'summer', line: 'Forty-one people received it. You prevented a credential compromise, and not just your own.' },
      { characterId: 'rick', line: 'Okay. Fine. That was... the correct call.', direction: 'He says it like it physically hurts.' },
    ],
    'You verified nothing and trusted nothing — which is exactly right, because the sender name, the logo and the layout are all free for an attacker to copy. The one thing they cannot fake is the reporting channel. Reporting also turns your single decision into protection for everyone else who got the same message.',
    ['K-PHI-01', 'K-INC-01'],
    's2_intro',
    ['summer', 'rick'],
    'Summer has two minutes before her next meeting. Ask her anything.',
  ),
  consequence(
    'c1_reply',
    1,
    shot(
      'desk',
      'morning',
      'tense',
      'Over-shoulder shot of a reply being typed: "Hi, can you confirm this is genuine?". Send. Beat. A reply arrives within forty seconds. Slow push in on the too-fast response. Unsettling stillness.',
    ),
    'mixed',
    'VERIFIED — BY THE ATTACKER',
    [
      { characterId: 'you', line: 'You ask them to confirm. They confirm. Enthusiastically. In under a minute.' },
      { characterId: 'morty', line: 'That was fast. Is IT normally that fast? IT is never that fast.', direction: 'He is right, and he knows he is right, and he still sounds apologetic about it.' },
      { characterId: 'summer', line: 'You did try to verify, and that instinct is the right one. But you verified with the person who sent it. You also confirmed to an attacker that this mailbox is live and that someone here answers.', direction: 'She pulls up a chair without being invited.' },
    ],
    'Your instinct — do not act on an unexpected request until it is confirmed — was the right one. The execution handed the attacker the verification channel. Verification only works through a channel you already trusted before the message arrived: the directory, the Service Desk number on your badge, a walk to someone’s desk. Never the contact details inside the request.',
    ['K-SOC-01', 'K-PHI-01'],
    's2_intro',
    ['summer', 'morty'],
    'Push back on her if you disagree. She likes that.',
  ),
]

/* -------------------------------------------------------------------------- */
/* ACT 2 — THE FAST WAY                                                        */
/* -------------------------------------------------------------------------- */

const act2: Scene[] = [
  {
    id: 's2_intro',
    kind: 'cinematic',
    act: 2,
    title: 'THE FAST WAY',
    subtitle: '13:40 · OPERATIONS POD',
    shot: shot(
      'open_office',
      'midday',
      'neutral',
      'Steady wide of an operations pod after lunch: four monitors, a whiteboard covered in a renewal funnel, harsh midday light through blinds cutting stripes across the room. A lead leans back in his chair to talk over the divider. Naturalistic, documentary framing.',
    ),
    dialogue: [
      { characterId: 'jerry', line: 'You’re the new associate. Jerry, customer ops. I need eleven hundred support tickets summarised by five and I have you for an hour. Congratulations.', direction: 'He has already sent you the file.' },
      { characterId: 'jerry', line: "Here's the export — names, emails, account ids, free-text complaints. Just paste it into that AI summariser everybody uses. It does in four minutes what takes me an afternoon." },
      { characterId: 'you', line: 'The file is open. Two thousand rows of other people’s lives.' },
      { characterId: 'jerry', line: "Half the floor uses it. It's fine. I'd do it myself but I'm on a call in ninety seconds." },
    ],
    next: 'd2_tool',
  },
  {
    id: 'd2_tool',
    kind: 'decision',
    act: 2,
    title: 'THE EXPORT',
    threat: { source: 'internal', pressure: 'peer' },
    shot: shot(
      'open_office',
      'midday',
      'tense',
      'Extreme close-up of a spreadsheet of customer records, cursor selecting all. Cut to a browser tab open on a consumer AI chat box, cursor hovering over the paste target. Ticking clock energy, tight framing, warm-to-cold colour shift.',
    ),
    dialogue: [{ characterId: 'jerry', line: 'Clock’s running. What do you need from me?' }],
    prompt: 'WHAT DO YOU DO?',
    allowWager: true,
    choices: [
      choice({
        id: 'd2_a',
        label: 'A',
        text: 'Paste the export into the external AI tool. Everyone else does.',
        consequenceSceneId: 'c2_paste',
        knowledgeConcepts: ['data_handling', 'approved_tools'],
        scoreImpact: -14,
        quality: 'poor',
        ledgerLabel: 'Sent customer data to an unapproved tool',
      }),
      choice({
        id: 'd2_b',
        label: 'B',
        text: 'Do it in Helix Assist instead, and tell Jerry why.',
        consequenceSceneId: 'c2_assist',
        knowledgeConcepts: ['approved_tools', 'data_handling'],
        scoreImpact: 14,
        quality: 'best',
        ledgerLabel: 'Used an approved tool for customer data',
      }),
      choice({
        id: 'd2_c',
        label: 'C',
        text: 'Ask whether that tool has actually been approved before using it.',
        consequenceSceneId: 'c2_ask',
        knowledgeConcepts: ['approved_tools'],
        scoreImpact: 8,
        quality: 'acceptable',
        ledgerLabel: 'Checked tool approval before acting',
      }),
    ],
  },
  consequence(
    'c2_paste',
    2,
    shot(
      'open_office',
      'dusk',
      'alarm',
      'Fast cut: paste, spinner, a clean summary appearing. Relief. Then slow dissolve to a legal-review meeting room three weeks later, a lawyer sliding a printed page across a table, timestamp visible. Cold institutional light, colour draining out.',
    ),
    'bad',
    'REPORTABLE DATA BREACH',
    [
      { characterId: 'you', line: 'Four minutes. The summary is genuinely excellent. Jerry is delighted.' },
      { characterId: 'jerry', line: 'See? This is why I like new people. Send it to me and go get a coffee.' },
      { characterId: 'summer', line: 'Three weeks later, Security runs a routine egress review.', direction: 'HARD CUT — a meeting room. Nobody is shouting. That is somehow worse.' },
      { characterId: 'summer', line: 'Two thousand one hundred and forty customer records left our approved systems through a consumer account with no data processing agreement. We now have to notify. Not because anything was stolen — because we cannot prove it was not.', direction: 'She does not look at you unkindly. She looks tired.' },
    ],
    'The tool worked. That was never the question. Once customer data leaves an approved system, Helix loses control of retention, deletion and jurisdiction — and under our customer agreements that is a reportable breach whether or not anyone misused it. "Half the floor uses it" describes a gap in enforcement, not an approval. Helix Assist exists precisely so the fast path and the legal path are the same path.',
    ['K-DAT-01', 'K-TOL-01', 'K-TOL-02'],
    's3_gate',
    ['summer', 'jerry'],
    'Ask Summer why the tool being good doesn’t matter.',
  ),
  consequence(
    'c2_assist',
    2,
    shot(
      'open_office',
      'midday',
      'calm',
      'Confident insert: the same data loading inside an internal tool with a compliance banner. Summary generates. Cut to a two-shot of the lead reading it over a shoulder, nodding, the tension leaving his posture. Warm practical light, relaxed handheld.',
    ),
    'good',
    'SAME SPEED. NO EXPOSURE.',
    [
      { characterId: 'you', line: 'Helix Assist. Same paste, different building.' },
      { characterId: 'jerry', line: 'Huh. Six minutes instead of four, and it stays inside the fence.', direction: 'He reads it twice. It is better than what he would have written.' },
      { characterId: 'jerry', line: "Nobody explained it like that. They just sent a policy PDF that said 'do not use unapproved tools' and I decided it was legal being precious. Fine. I'm converted. Tell the others." },
      { characterId: 'summer', line: 'Logged as approved processing. No notification, no review, no lawyers. Good.', direction: 'From two desks away, without looking up.' },
    ],
    'The winning move was not refusing the task — it was refusing the container. Helix Assist runs under a no-training agreement with a thirty-day retention limit, which is what makes the same paste legal. You also did the part policy cannot do on its own: you gave a colleague the reason, so the next eleven hundred tickets go the right way without you.',
    ['K-TOL-02', 'K-DAT-01'],
    's3_gate',
    ['jerry', 'summer'],
    'Jerry is curious now. Ask him what else his team does this way.',
  ),
  consequence(
    'c2_ask',
    2,
    shot(
      'open_office',
      'midday',
      'neutral',
      'Two-shot across a desk divider, the question landing. A pause. Cut to a browser opening an internal catalogue page, search field, a red UNREVIEWED badge resolving on screen. Even daylight, unhurried.',
    ),
    'mixed',
    'GOOD QUESTION. NOBODY HAD ASKED IT.',
    [
      { characterId: 'you', line: '"Before I paste two thousand customer records into it — has that tool actually been approved?"' },
      { characterId: 'jerry', line: '...I assumed. Which, now that I hear myself say it out loud, is not the same as knowing.', direction: 'He pulls up the Approved Tools Catalogue. Searches. UNREVIEWED.' },
      { characterId: 'jerry', line: "Eight months I've been using that. Right. Helix Assist it is. Slower to type, faster than a legal review." },
      { characterId: 'rick', line: 'The new one just audited customer ops on day one.', direction: 'Delighted. From somewhere behind a monitor.' },
    ],
    'Asking was enough to stop it, and that is worth knowing: you do not need to win an argument about policy, you only need to make the assumption visible. The one gap is that you needed Jerry to check for you — the Approved Tools Catalogue is self-serve, and checking it takes about fifteen seconds. Popularity is not approval; a free tier still processes company data.',
    ['K-TOL-01', 'K-DAT-01'],
    's3_gate',
    ['jerry'],
    'Ask Jerry what he would have done if you hadn’t asked.',
  ),
]

/* -------------------------------------------------------------------------- */
/* ACT 3 — ADAPTIVE SLOT                                                       */
/* The engine selects a branch from the player's weakest demonstrated concept.  */
/* -------------------------------------------------------------------------- */

const act3: Scene[] = [
  {
    id: 's3_gate',
    kind: 'cinematic',
    act: 3,
    title: 'ADAPTING',
    subtitle: 'READING YOUR DECISIONS',
    shot: shot('corridor', 'dusk', 'neutral', 'Transitional corridor walk, late afternoon light through slatted glass, figures blurring past.'),
    dialogue: [],
    variants: [
      { conceptFocus: 'password_security', sceneId: 's3_creds' },
      { conceptFocus: 'social_engineering', sceneId: 's3_call' },
      { conceptFocus: 'data_handling', sceneId: 's3_export' },
    ],
  },

  /* --- variant A: credential sharing ------------------------------------- */
  {
    id: 's3_creds',
    kind: 'cinematic',
    act: 3,
    title: 'THE FAVOUR',
    subtitle: '16:20 · RICK’S DESK',
    shot: shot(
      'desk',
      'dusk',
      'tense',
      'Low warm afternoon light raking across a cluttered engineer’s desk, three monitors, a failing deploy pipeline in red. A senior engineer spins his chair to face camera, too close, friendly. Shallow focus, 40mm, amber grade.',
    ),
    dialogue: [
      { characterId: 'rick', line: 'Okay. Favour. My deploy access got revoked this morning — some access review thing, total theatre — and there is a customer-facing bug in production right now.', direction: 'The pipeline behind him is a wall of red.' },
      { characterId: 'rick', line: 'Your account has the group. Just log me in, I push the one-line fix, you watch me do it, we never speak of it again.' },
      { characterId: 'rick', line: 'I wrote this service. I am not the threat here. The threat is the bug.', direction: 'He is not wrong about the bug.' },
    ],
    next: 'd3_creds',
  },
  {
    id: 'd3_creds',
    kind: 'decision',
    act: 3,
    title: 'BORROWED ACCESS',
    threat: { source: 'internal', pressure: 'authority' },
    shot: shot('desk', 'dusk', 'tense', 'Insert: an SSO prompt on screen, a hand hovering over a keyboard that is not the owner’s. Held too long.'),
    dialogue: [{ characterId: 'rick', line: 'Customers are seeing errors while we discuss this.' }],
    prompt: 'WHAT DO YOU DO?',
    allowWager: true,
    choices: [
      choice({
        id: 'd3c_a',
        label: 'A',
        text: 'Log in and let him push the fix while you watch.',
        consequenceSceneId: 'c3c_share',
        knowledgeConcepts: ['password_security', 'social_engineering'],
        scoreImpact: -15,
        quality: 'poor',
        ledgerLabel: 'Shared account access with a colleague',
      }),
      choice({
        id: 'd3c_b',
        label: 'B',
        text: 'Refuse, and raise a break-glass access request with the on-call manager.',
        consequenceSceneId: 'c3c_glass',
        knowledgeConcepts: ['password_security', 'incident_reporting'],
        scoreImpact: 15,
        quality: 'best',
        ledgerLabel: 'Protected account integrity under pressure',
      }),
      choice({
        id: 'd3c_c',
        label: 'C',
        text: 'Refuse the login, but push his one-line fix yourself under your own account.',
        consequenceSceneId: 'c3c_proxy',
        knowledgeConcepts: ['password_security'],
        scoreImpact: 2,
        quality: 'acceptable',
        ledgerLabel: 'Kept credentials, but acted as a proxy',
      }),
    ],
  },
  consequence(
    'c3c_share',
    3,
    shot('desk', 'night', 'alarm', 'Night office. An audit log on a large screen, one username highlighted repeatedly in a long list of actions. Cold monitor light on a still face.'),
    'bad',
    'ATTRIBUTION LOST',
    [
      { characterId: 'rick', line: 'Thirty seconds. Done. You are a good person and I will deny this conversation.' },
      { characterId: 'summer', line: '22:10. The one-line fix took down checkout in three regions for nineteen minutes. Rollback is finished. Now we do the boring part.', direction: 'The office is dark except for her screen.' },
      { characterId: 'summer', line: 'The audit log says you did it. Every action, your account, your session. I believe you that it was Rick. I cannot prove it, and neither can you. That is the entire reason the rule exists.', direction: 'She is not shouting. Nobody ever shouts here. It is much worse.' },
    ],
    'Access was revoked on purpose — that was the control working, not a bug in it. Sharing a session does not just bypass a permission, it destroys attribution: the log records your identity performing someone else’s actions, so a nineteen-minute outage becomes something you cannot explain your way out of. Genuine emergencies are exactly what break-glass access is for, and it takes minutes.',
    ['K-PWD-01', 'K-INC-01'],
    's4_intro',
    ['summer', 'rick'],
    'Ask Summer what you should have done with a real production bug.',
  ),
  consequence(
    'c3c_glass',
    3,
    shot('desk', 'dusk', 'calm', 'A phone call made standing up, pipeline red behind, then green. Two engineers watching a deploy log scroll. Relief in the body language, warm dusk light.'),
    'good',
    'HELD THE LINE — FIXED THE BUG',
    [
      { characterId: 'you', line: '"I’m not logging you in. I am calling the on-call manager right now and getting you break-glass."' },
      { characterId: 'rick', line: 'That is going to take—', direction: 'It takes six minutes.' },
      { characterId: 'rick', line: 'Six minutes. Under my own account. With an approved reason attached. Fine. I hate that that was better.', direction: 'The pipeline goes green. He does not thank you, which is how you know he means it.' },
      { characterId: 'summer', line: 'Break-glass request at 16:31, closed 16:52, full attribution. That is the best thing that happened on this floor today.', direction: 'Slack DM. One line.' },
    ],
    'You separated the two things Rick had deliberately fused: the bug is urgent, but sharing your account is not the only fast path. Break-glass access exists so urgency does not have to cost attribution — Rick acted under his own identity, with a logged reason, in six minutes. Refusing was not obstruction; it was finding the version of yes that leaves a record.',
    ['K-PWD-01', 'K-SOC-01'],
    's4_intro',
    ['rick', 'summer'],
    'Rick is grudgingly impressed. Ask him why he thought it was fine.',
  ),
  consequence(
    'c3c_proxy',
    3,
    shot('desk', 'dusk', 'neutral', 'Over-shoulder: someone typing a change they did not write, reading it from a colleague’s screen. A brief hesitation before the enter key.'),
    'mixed',
    'YOUR ACCOUNT. HIS CHANGE.',
    [
      { characterId: 'you', line: 'You keep your password and push his diff yourself. It is one line. You are almost sure you understand it.' },
      { characterId: 'rick', line: 'Close enough. Ship it.' },
      { characterId: 'summer', line: 'Credentials intact — genuinely, well held. But the log now says you authored a production change you did not write and could not review. That is a smaller version of the same problem.', direction: 'She writes something down.' },
      { characterId: 'summer', line: 'The fix worked, so nobody will notice this time. Notice it anyway.' },
    ],
    'Protecting your credentials was the right instinct and the hard part — you did it under real pressure. What remained was accountability: acting as a human proxy still puts your name on work you could not verify. Break-glass access would have given Rick his own attributed session in minutes, which is faster than the review you owed that diff.',
    ['K-PWD-01', 'K-INC-01'],
    's4_intro',
    ['summer', 'rick'],
    'Ask Summer where the line is between helping and proxying.',
  ),

  /* --- variant B: voice phishing ----------------------------------------- */
  {
    id: 's3_call',
    kind: 'cinematic',
    act: 3,
    title: 'THE CALL',
    subtitle: '16:20 · DESK PHONE',
    shot: shot(
      'desk',
      'dusk',
      'tense',
      'Close on a desk phone lighting up, INTERNAL on the display. Dusk through the blinds. Room sound drops away as the handset is lifted. Very shallow focus, tight on the ear and jaw.',
    ),
    dialogue: [
      { characterId: 'you', line: 'The phone on your desk rings for the first time. The display says INTERNAL.' },
      { characterId: 'rick', line: "Helix IT Service Desk, this is Aaron. We're seeing repeated failed logins on your account from outside the country — are you travelling?", direction: 'Not Rick. A voice you have never heard, doing an extremely good job of sounding bored and helpful.' },
      { characterId: 'rick', line: "Okay, so that's not you. I'm locking the session down now. I need the six-digit code on your authenticator to push the revocation through before it expires." },
      { characterId: 'rick', line: "I know, it's unusual, I'll wait. It just has to be in the next thirty seconds or the token cycles and we start over.", direction: 'He sounds like he does this forty times a day. He does.' },
    ],
    next: 'd3_call',
  },
  {
    id: 'd3_call',
    kind: 'decision',
    act: 3,
    title: 'THE SIX DIGITS',
    threat: { source: 'external', pressure: 'authority' },
    shot: shot('desk', 'dusk', 'tense', 'Insert: authenticator app, six digits, countdown ring draining. Held on the shrinking circle.'),
    dialogue: [{ characterId: 'rick', line: 'Still there? Twenty seconds.' }],
    prompt: 'WHAT DO YOU DO?',
    allowWager: true,
    choices: [
      choice({
        id: 'd3l_a',
        label: 'A',
        text: 'Read out the code. He called you, and he is locking the attacker out.',
        consequenceSceneId: 'c3l_give',
        knowledgeConcepts: ['password_security', 'social_engineering'],
        scoreImpact: -16,
        quality: 'poor',
        ledgerLabel: 'Disclosed an MFA code over the phone',
      }),
      choice({
        id: 'd3l_b',
        label: 'B',
        text: 'Hang up, call the Service Desk on the number on your badge, and report the call.',
        consequenceSceneId: 'c3l_hangup',
        knowledgeConcepts: ['social_engineering', 'incident_reporting'],
        scoreImpact: 16,
        quality: 'best',
        ledgerLabel: 'Refused and reported a vishing attempt',
      }),
      choice({
        id: 'd3l_c',
        label: 'C',
        text: 'Refuse the code, but stay on the line and answer his other questions.',
        consequenceSceneId: 'c3l_stay',
        knowledgeConcepts: ['social_engineering'],
        scoreImpact: 3,
        quality: 'acceptable',
        ledgerLabel: 'Withheld the code, kept talking',
      }),
    ],
  },
  consequence(
    'c3l_give',
    3,
    shot('desk', 'night', 'alarm', 'The line goes dead mid-thank-you. Cut to a security dashboard: a new authenticated session, unfamiliar city, timestamp two seconds old. Cold red wash.'),
    'bad',
    'ACCOUNT TAKEOVER',
    [
      { characterId: 'rick', line: "Perfect, that's gone through, you're all set — thanks for your—", direction: 'The line cuts before the sentence finishes.' },
      { characterId: 'you', line: 'You sit with the handset in your hand for a second longer than feels good.' },
      { characterId: 'summer', line: 'There was never a failed login from abroad. He had your password already — that part was real. What he was missing was the second factor, and you read it to him while he sat on your login screen.', direction: 'She is watching a session she is about to kill.' },
      { characterId: 'summer', line: 'Eleven minutes of access. Mail, drive, the internal directory. You are not the first and you will not be the last. Report it now and we contain it.' },
    ],
    'The call was the attack. No Helix system, employee or support agent will ever ask you to read out an MFA code — the request itself is the signal, regardless of how the call arrives or how plausible the caller sounds. An inbound call is not identification: a display saying INTERNAL is trivially spoofed. The thirty-second deadline existed only to stop you thinking.',
    ['K-PWD-02', 'K-PHI-02', 'K-INC-01'],
    's4_intro',
    ['summer', 'morty'],
    'Ask Summer how you were supposed to tell.',
  ),
  consequence(
    'c3l_hangup',
    3,
    shot('desk', 'dusk', 'calm', 'The handset going down deliberately. A badge turned over to read the printed number. A second call, calm, standing. Warm dusk light returning to the room.'),
    'good',
    'ATTACK STOPPED COLD',
    [
      { characterId: 'you', line: '"I’m going to hang up and call the Service Desk myself." You do it before he can answer.' },
      { characterId: 'summer', line: 'Service Desk had no open ticket for you. Nobody called you. We have had six of those calls today — you are the first person to hang up.', direction: 'She is already writing the floor-wide advisory.' },
      { characterId: 'summer', line: 'Two people gave codes. They are fine now, because they also reported it. You gave us the pattern.' },
      { characterId: 'morty', line: 'Wait, they call people? On the actual phone? I would have—', direction: 'He stops. He would have.' },
    ],
    'You did the one thing the script cannot survive: you left the channel the attacker controlled. Hanging up and dialling the number on your own badge means verification happens somewhere they cannot follow. The deadline, the helpfulness and the plausible story were all pressure engineering, and you treated urgency itself as the warning sign.',
    ['K-PWD-02', 'K-SOC-01', 'K-INC-01'],
    's4_intro',
    ['summer', 'rick'],
    'Ask Summer how these calls usually start.',
  ),
  consequence(
    'c3l_stay',
    3,
    shot('desk', 'dusk', 'neutral', 'A conversation continuing past the point of comfort. Notes being taken on a pad. The caller’s voice, warm and patient, filling the frame.'),
    'mixed',
    'HELD THE CODE. GAVE HIM THE MAP.',
    [
      { characterId: 'you', line: '"I’m not reading you a code." He takes it well. Suspiciously well.' },
      { characterId: 'rick', line: "Totally fair, I wouldn't either. Let's do it another way — who's your line manager, what team are you on, and are you on the old VPN or the new one?", direction: 'He writes all of it down. So do you, but only one of you benefits.' },
      { characterId: 'summer', line: 'Good refusal. But you then confirmed your team, your manager’s name and which VPN estate you are on. That is the next email he sends, and it will be a very convincing one.', direction: 'She flags your account for monitoring.' },
    ],
    'Refusing the code was the decision that mattered and you made it under pressure. The gap is that the call kept going: once a request is suspect, everything after it is reconnaissance, and organisational detail is what turns a generic phish into a targeted one. Verification means ending the untrusted channel, not negotiating inside it.',
    ['K-PWD-02', 'K-SOC-01'],
    's4_intro',
    ['summer'],
    'Ask Summer what she would have done on that call.',
  ),

  /* --- variant C: bulk export -------------------------------------------- */
  {
    id: 's3_export',
    kind: 'cinematic',
    act: 3,
    title: 'THE WEEKEND',
    subtitle: '16:20 · OPERATIONS POD',
    shot: shot(
      'open_office',
      'dusk',
      'tense',
      'Late afternoon, half the desks empty, monitors going to sleep in a row. A lead packing a bag while still talking. Long amber light, end-of-day exhaustion in the frame.',
    ),
    dialogue: [
      { characterId: 'jerry', line: 'Last thing and then I genuinely leave. The renewals deck is due Monday 9am and I am on a plane all weekend.', direction: 'He is already standing.' },
      { characterId: 'jerry', line: "Pull the full customer table — all of it, easier than filtering — drop it in my personal cloud drive and I'll work on it from the hotel. Laptop stays here, I only have my tablet." },
      { characterId: 'jerry', line: "It's my own data, effectively. I'm the one who owns those accounts." },
    ],
    next: 'd3_export',
  },
  {
    id: 'd3_export',
    kind: 'decision',
    act: 3,
    title: 'THE FULL TABLE',
    threat: { source: 'internal', pressure: 'authority' },
    shot: shot('open_office', 'dusk', 'tense', 'Insert: a query editor, SELECT * with no WHERE clause, row count climbing past two hundred thousand. Cursor over EXPORT.'),
    dialogue: [{ characterId: 'jerry', line: 'I have a taxi in four minutes.' }],
    prompt: 'WHAT DO YOU DO?',
    allowWager: true,
    choices: [
      choice({
        id: 'd3e_a',
        label: 'A',
        text: 'Export the full table to his personal drive. He owns those accounts.',
        consequenceSceneId: 'c3e_export',
        knowledgeConcepts: ['data_handling', 'approved_tools'],
        scoreImpact: -15,
        quality: 'poor',
        ledgerLabel: 'Bulk-exported customer data off approved systems',
      }),
      choice({
        id: 'd3e_b',
        label: 'B',
        text: 'Refuse the export; give him a filtered dashboard he can open on his tablet.',
        consequenceSceneId: 'c3e_dash',
        knowledgeConcepts: ['data_handling'],
        scoreImpact: 15,
        quality: 'best',
        ledgerLabel: 'Minimised data and kept it in-system',
      }),
      choice({
        id: 'd3e_c',
        label: 'C',
        text: 'Export only the fifty accounts up for renewal, still to his personal drive.',
        consequenceSceneId: 'c3e_partial',
        knowledgeConcepts: ['data_handling'],
        scoreImpact: 1,
        quality: 'acceptable',
        ledgerLabel: 'Reduced the export, wrong destination',
      }),
    ],
  },
  consequence(
    'c3e_export',
    3,
    shot('open_office', 'night', 'alarm', 'An upload progress bar completing in an empty office. Dissolve to a hotel room at night, a tablet on a bed, a shared-link dialog open. Cold blue, quiet dread.'),
    'bad',
    '214,000 RECORDS, UNMANAGED',
    [
      { characterId: 'you', line: 'The export finishes at 16:44. Two hundred and fourteen thousand rows, sitting in a personal cloud account.' },
      { characterId: 'jerry', line: 'You are a lifesaver. Sending you the deck Monday.', direction: 'From the taxi. He means it kindly.' },
      { characterId: 'summer', line: "Monday. His drive is shared with his partner's laptop for photo backup. Sync picked up the file at 21:12 on Saturday. That device is not managed by us and is not encrypted.", direction: 'A diagram on her screen, one arrow leaving a box.' },
      { characterId: 'summer', line: 'Nothing has been stolen. We still have to write to a regulator, because we cannot describe where that data is.' },
    ],
    'Two separate rules failed at once: the data left approved systems, and the export was far larger than the task required. "Easier than filtering" is how small requests become large breaches — a renewals deck needed about fifty accounts, not the whole table. Personal cloud storage is unmanaged by definition; the sync you cannot see is the one that moves the file.',
    ['K-DAT-01', 'K-DAT-02', 'K-TOL-01'],
    's4_intro',
    ['summer', 'jerry'],
    'Ask Summer why "he owns the accounts" isn’t enough.',
  ),
  consequence(
    'c3e_dash',
    3,
    shot('open_office', 'dusk', 'calm', 'A dashboard being built quickly, filters snapping into place, a share link generated with an access banner. Cut to a tablet in an airport lounge showing the same view. Warm, competent, fluid.'),
    'good',
    'SHE GETS HER DECK. NOTHING LEAVES.',
    [
      { characterId: 'you', line: 'Four minutes: fifty renewal accounts, filtered, a saved view, SSO link. No file. No export.' },
      { characterId: 'jerry', line: 'This opens on my tablet. With my login. From an airport.', direction: 'A pause on the line.' },
      { characterId: 'jerry', line: 'This is better than what I asked for. Why does nobody build it this way the first time?' },
      { characterId: 'summer', line: 'Zero rows exported today from your account. Have a good weekend.', direction: 'Automated digest. She added the last sentence by hand.' },
    ],
    'You solved the actual problem — he needed to see the data, not to possess a copy of it. Keeping processing inside approved systems preserves access control, logging and deletion, and filtering to the fifty accounts the task needed satisfies minimisation at the same time. The constraint produced a better answer than the shortcut would have.',
    ['K-DAT-01', 'K-DAT-02'],
    's4_intro',
    ['jerry', 'summer'],
    'Ask Jerry why the shortcut felt reasonable to him.',
  ),
  consequence(
    'c3e_partial',
    3,
    shot('open_office', 'dusk', 'neutral', 'A much smaller file uploading. Fifty rows on screen, names legible. A beat of hesitation before the upload completes.'),
    'mixed',
    'SMALLER. STILL OUTSIDE.',
    [
      { characterId: 'you', line: 'Fifty rows instead of two hundred thousand. You feel notably better about this.' },
      { characterId: 'jerry', line: 'Perfect, that is all I needed anyway. Thank you!', direction: 'Taxi door. Gone.' },
      { characterId: 'summer', line: 'Minimisation: good, and it genuinely reduces the damage. Destination: still an unmanaged personal drive we cannot audit or delete from.', direction: 'She does not escalate it. She does log it.' },
      { characterId: 'summer', line: 'Fifty people is a small breach rather than a large one. It is still a breach we would have to describe.' },
    ],
    'You applied data minimisation under time pressure, which is the harder half and most people skip it. The remaining problem is the destination rather than the volume: any personal cloud account is outside Helix control, so retention and deletion stop being things we can promise. An in-system filtered view would have got him the same fifty accounts with none of that.',
    ['K-DAT-02', 'K-DAT-01'],
    's4_intro',
    ['summer', 'jerry'],
    'Ask Summer whether fifty records really matters.',
  ),
]

/* -------------------------------------------------------------------------- */
/* ACT 4 — END OF DAY                                                          */
/* -------------------------------------------------------------------------- */

const act4: Scene[] = [
  {
    id: 's4_intro',
    kind: 'cinematic',
    act: 4,
    title: 'END OF DAY',
    subtitle: '18:05 · STAIRWELL',
    shot: shot(
      'night_office',
      'night',
      'tense',
      'Concrete stairwell at night, one fluorescent tube humming, two figures on a landing lit from above. Intimate, confessional framing. Green-tinted practical light, quiet room tone.',
    ),
    dialogue: [
      { characterId: 'morty', line: "Can I tell you something and you don't tell anyone?", direction: 'He has been waiting on the landing for you.' },
      { characterId: 'morty', line: 'That email this morning. I got one on Thursday too. Same kind of thing. And I... clicked it. I typed my password in and then the page just went blank and I closed the laptop.', direction: 'He says it very fast, like it hurts less that way.' },
      { characterId: 'morty', line: "Nothing happened. Four days, nothing. If I report it now they'll know I sat on it for four days in my first week. I'll be the guy who did that." },
      { characterId: 'you', line: 'Four days. Nothing happened that he can see.' },
    ],
    next: 'd4_report',
  },
  {
    id: 'd4_report',
    kind: 'decision',
    act: 4,
    title: 'FOUR DAYS LATE',
    threat: { source: 'internal', pressure: 'peer' },
    shot: shot('night_office', 'night', 'tense', 'Two-shot on the landing, both faces half in shadow. The decision sits in the silence between them.'),
    dialogue: [{ characterId: 'morty', line: 'What would you do?' }],
    prompt: 'WHAT DO YOU DO?',
    allowWager: true,
    choices: [
      choice({
        id: 'd4_a',
        label: 'A',
        text: 'Tell him to let it go. Four days of nothing means nothing happened.',
        consequenceSceneId: 'c4_bury',
        knowledgeConcepts: ['incident_reporting'],
        scoreImpact: -14,
        quality: 'poor',
        ledgerLabel: 'Suppressed a security incident',
      }),
      choice({
        id: 'd4_b',
        label: 'B',
        text: 'Walk him to the Security Portal now and report it together.',
        consequenceSceneId: 'c4_report',
        knowledgeConcepts: ['incident_reporting', 'phishing'],
        scoreImpact: 15,
        quality: 'best',
        ledgerLabel: 'Reported a colleague’s incident, with him',
      }),
      choice({
        id: 'd4_c',
        label: 'C',
        text: 'Report it yourself, quietly, without telling him.',
        consequenceSceneId: 'c4_solo',
        knowledgeConcepts: ['incident_reporting'],
        scoreImpact: 6,
        quality: 'acceptable',
        ledgerLabel: 'Reported it — behind his back',
      }),
    ],
  },
  consequence(
    'c4_bury',
    4,
    shot('night_office', 'night', 'alarm', 'A stairwell emptying. Dissolve through darkness to a morning all-hands screen: INCIDENT NOTICE. Faces in rows, no sound. Desaturated, wide, impersonal.'),
    'bad',
    'DAY 11: INVOICE FRAUD',
    [
      { characterId: 'you', line: '"Four days, nothing happened. Let it go." He exhales like you have lifted a car off him.' },
      { characterId: 'morty', line: 'Thank you. Genuinely. I have not slept properly since Thursday.', direction: 'It is the happiest you will see him.' },
      { characterId: 'summer', line: "Eleven days after Morty's click, someone using his mailbox emailed our largest customer new bank details. They paid. Two hundred and eighty thousand.", direction: 'All-hands. No names used. Everyone knows anyway.' },
      { characterId: 'summer', line: "The session token from Thursday was still valid. One report on Thursday would have cost us twenty minutes of revocation. We got it on day eleven, from the customer's finance team." },
    ],
    'Stolen credentials are rarely used immediately — the quiet gap is the attacker establishing access, and "nothing happened" is exactly what that looks like from the inside. Reporting is required within the hour because containment is cheap early and forensic later, and a password change alone would not have helped: live session tokens survive it and only IT can revoke them. Helix runs no-blame reporting so that the fear Morty felt is not a reason to stay silent.',
    ['K-INC-01', 'K-INC-02', 'K-PHI-01'],
    's_end',
    ['summer', 'morty'],
    'Ask Summer what the no-blame policy actually means in practice.',
  ),
  consequence(
    'c4_report',
    4,
    shot('night_office', 'night', 'calm', 'Two people at one desk in a dark office, a portal form open, one typing while the other reads over their shoulder. Warm pool of lamplight in a wide dark frame.'),
    'good',
    'CONTAINED ON DAY FOUR',
    [
      { characterId: 'you', line: '"We are reporting it now. Both of us. I will sit here while you type it."' },
      { characterId: 'morty', line: 'If I get fired on day four I am telling everyone it was your idea.', direction: 'He types it anyway. It takes ninety seconds.' },
      { characterId: 'summer', line: "Session tokens revoked, password rotated from a clean device, mailbox rules checked. There was one — a filter forwarding anything containing the word 'invoice'. It is gone now.", direction: 'She is in the office within the hour, and she brings food.' },
      { characterId: 'summer', line: 'Morty. Nobody is in trouble. Four days late beats four weeks late, and the only reason I know at all is that you told someone who told you to tell me.', direction: 'To you, quieter: "That is the part we cannot buy."' },
    ],
    'The forwarding rule is what a foothold looks like before it becomes fraud, and nothing but a report surfaces it — which is why the duty to report survives "nothing happened". A password change alone would have left the live session intact, so escalation was the only thing that closed it. You also did the culture part: no-blame reporting only works if colleagues actually tell each other, and you made reporting feel survivable rather than terminal.',
    ['K-INC-01', 'K-INC-02'],
    's_end',
    ['summer', 'morty'],
    'Ask Morty why he waited four days.',
  ),
  consequence(
    'c4_solo',
    4,
    shot('night_office', 'night', 'neutral', 'One person alone at a desk in a dark office filing a form. An empty landing behind them. Cool light, slight isolation in the framing.'),
    'mixed',
    'REPORTED. HE FOUND OUT FROM SECURITY.',
    [
      { characterId: 'you', line: 'You tell him it is fine. Then you file it from your desk twenty minutes later.' },
      { characterId: 'summer', line: 'Good report. Tokens revoked tonight, and there was a forwarding rule on his mailbox, so this mattered.', direction: 'Then, carefully: "How does Morty know?"' },
      { characterId: 'morty', line: 'Security called me. You said it was fine. Did you—', direction: 'He is not angry. He is recalculating who he can talk to, which is worse.' },
      { characterId: 'summer', line: 'You made the right call on the incident. Next time bring him with you. The reporting culture is the control; it only works if people are not afraid of each other.' },
    ],
    'Escalating was the right call and it worked — the report is what surfaced a live forwarding rule that a password change would not have touched. The cost was trust: reporting around a colleague teaches them that admitting a mistake gets handled behind their back, which is what makes the next person wait four days. No-blame reporting is a social control as much as a technical one.',
    ['K-INC-01', 'K-INC-02'],
    's_end',
    ['summer', 'morty'],
    'Ask Summer how to report someone else’s mistake without losing them.',
  ),
  {
    id: 's_end',
    kind: 'ending',
    act: 4,
    title: 'DAY ONE COMPLETE',
    subtitle: '18:40 · STREET LEVEL',
    shot: shot(
      'rooftop',
      'night',
      'calm',
      'Wide shot from street level: the building at night, most windows dark, one floor still lit. A figure walks out through the revolving door and stops on the pavement. City sound. Cool blue night, single warm window.',
    ),
    dialogue: [
      { characterId: 'you', line: 'Day one. You made four decisions that mattered and nobody told you which ones they were.' },
      { characterId: 'summer', line: 'See you tomorrow. It gets less dramatic. Slightly.', direction: 'Holding the door.' },
    ],
  },
]

const allScenes = [...act1, ...act2, ...act3, ...act4]

export const firstDay: Episode = {
  id: 'rm-ep01',
  number: 1,
  code: 'EPISODE 01',
  title: 'FIRST DAY',
  subtitle: 'Your first day is about to get complicated.',
  groupId: 'rick-and-morty',
  topic: 'Cybersecurity',
  duration: '6–8 min',
  locked: false,
  synopsis:
    'A suspicious email, a deadline, and a senior engineer who thinks policy is a rumour. Four decisions, none of them labelled.',
  concepts: ['phishing', 'password_security', 'data_handling', 'approved_tools', 'incident_reporting', 'social_engineering'],
  cast: ['morty', 'rick', 'jerry', 'summer'],
  entrySceneId: 's1_arrival',
  image: { src: '/episodes/rm-ep01.jpg', alt: 'FIRST DAY', focus: '50% 42%', credit: 'community wiki · prototype use only' },
  beats: [
    { act: 1, label: 'THE INBOX' },
    { act: 2, label: 'THE FAST WAY' },
    { act: 3, label: 'THE ASK' },
    { act: 4, label: 'END OF DAY' },
  ],
  scenes: Object.fromEntries(allScenes.map((s) => [s.id, s])),
}
