import { Film, Image as ImageIcon, Mic, Play, Shapes } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { getCharacter } from '@/content/characters'
import { attachAsset, DEFAULT_MAX_CLIPS, planEpisodeAssets, type AssetPlanItem } from '@/media/assetPlan'
import { audioProvider } from '@/media/audio'
import { imageProvider } from '@/media/image'
import { useMediaStatus } from '@/media/useMediaStatus'
import { awaitClip, clipSeconds, clipToAsset, requestClip, videoProvider } from '@/media/video'
import { resolveVoiceProfile } from '@/voice/voiceProfiles'
import type { AssetRef, Episode } from '@/types'
import { SceneCanvas } from '../SceneCanvas'
import { Btn, Chip } from '../ui/Bits'

/* ============================================================================
 * ASSET STUDIO — shot specs in, stored assets out, attached to the draft.
 *
 *   images  scene backgrounds + one keyframe per clip scene
 *   video   each keyframe animated into a ~5 s clip (image-to-video)
 *   voice   every character line
 *
 * Everything here happens before anyone plays. Each row states the tier it
 * actually got: generated by a model, or procedural previs.
 * ========================================================================== */

type RowStatus = 'queued' | 'rendering' | 'generated' | 'procedural' | 'runtime' | 'blocked' | 'failed'
interface Row {
  status: RowStatus
  note?: string
  startedAt?: number
}

const STATUS_CHIP: Record<RowStatus, { tone: 'good' | 'signal' | 'danger' | 'neutral' | 'cyan'; label: string }> = {
  queued: { tone: 'signal', label: 'queued' },
  rendering: { tone: 'signal', label: 'rendering…' },
  generated: { tone: 'good', label: 'ai generated · stored' },
  procedural: { tone: 'neutral', label: 'procedural previs' },
  runtime: { tone: 'neutral', label: 'runtime voice' },
  blocked: { tone: 'signal', label: 'needs scene image' },
  failed: { tone: 'danger', label: 'failed' },
}

function RowChip({ row, now }: { row?: Row; now: number }) {
  if (!row) return <Chip>waiting</Chip>
  const c = STATUS_CHIP[row.status]
  const live = (row.status === 'queued' || row.status === 'rendering') && row.startedAt
  return (
    <Chip tone={c.tone}>
      {c.label}
      {live ? ` ${Math.round((now - row.startedAt!) / 1000)}s` : ''}
    </Chip>
  )
}

/** Ticks while something is rendering, so elapsed times stay honest. */
function useNow(active: boolean) {
  const [now, setNow] = useState(Date.now())
  useEffect(() => {
    if (!active) return
    const t = setInterval(() => setNow(Date.now()), 1000)
    return () => clearInterval(t)
  }, [active])
  return now
}

async function pool<T>(items: T[], size: number, work: (item: T) => Promise<void>) {
  const queue = [...items]
  const worker = async () => {
    for (let item = queue.shift(); item !== undefined; item = queue.shift()) await work(item)
  }
  await Promise.all(Array.from({ length: Math.min(size, items.length) }, worker))
}

function AssetRow({ episode, item, row, now, detail }: { episode: Episode; item: AssetPlanItem; row?: Row; now: number; detail?: string }) {
  const scene = episode.scenes[item.sceneId]
  return (
    <div className="flex items-center gap-3 border border-bone/8 bg-ink-900/30 p-2.5" data-asset-row={item.key}>
      <div className="relative aspect-video w-28 shrink-0 overflow-hidden border border-bone/10 sm:w-40">
        <SceneCanvas shot={scene.shot} sceneKey={`thumb-${item.key}`} paused assets={item.kind === 'image' ? { background: scene.assets?.background } : scene.assets} />
      </div>
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-2">
          <span className="font-mono text-[9px] uppercase tracking-[0.14em] text-signal">
            {item.kind === 'video' ? 'clip' : item.key.startsWith('image:keyframe') ? 'keyframe' : 'background'}
          </span>
          <span className="truncate font-sans text-[12.5px] text-bone">{scene.title ?? scene.outcome?.banner ?? scene.id}</span>
          <span className="font-mono text-[9px] text-bone-faint">
            {item.reason}
            {item.sceneIds.length > 1 ? ` · ×${item.sceneIds.length} scenes` : ''}
            {detail ? ` · ${detail}` : ''}
          </span>
        </div>
        <p className="mt-1 line-clamp-2 font-sans text-[11px] font-light leading-snug text-bone-faint">{item.prompt}</p>
        {row?.note && <p className="mt-0.5 truncate font-mono text-[9px] text-bone-faint">{row.note}</p>}
      </div>
      <RowChip row={row} now={now} />
    </div>
  )
}

/* ------------------------------------------------------------------ images */

export function VisualAssets({ episode, onChange }: { episode: Episode; onChange: (ep: Episode) => void }) {
  const { health } = useMediaStatus()
  const plan = useMemo(() => planEpisodeAssets(episode).filter((i) => i.kind === 'image'), [episode.id]) // eslint-disable-line react-hooks/exhaustive-deps
  const [rows, setRows] = useState<Record<string, Row>>({})
  const [running, setRunning] = useState(false)
  const now = useNow(running)
  const image = imageProvider()
  const live = image.tier === 'generated'
  const keyframes = plan.filter((i) => i.key.startsWith('image:keyframe'))
  const backgrounds = plan.filter((i) => !i.key.startsWith('image:keyframe'))

  async function run() {
    setRunning(true)
    let current = episode
    const set = (key: string, row: Row) => setRows((r) => ({ ...r, [key]: row }))
    await pool(plan, 4, async (item) => {
      set(item.key, { status: 'rendering', startedAt: Date.now() })
      const { asset, error } = await image.generateBackground({ episodeId: current.id, sceneId: item.sceneId, prompt: item.prompt })
      if (!asset) return set(item.key, { status: 'failed', note: error })
      current = attachAsset(current, item, asset)
      onChange(current)
      set(item.key, { status: asset.tier === 'generated' ? 'generated' : 'procedural', note: asset.storageKey })
    })
    setRunning(false)
  }

  const finished = plan.length > 0 && plan.every((i) => rows[i.key] && rows[i.key].status !== 'rendering')

  return (
    <div>
      <div className={`glass flex items-start gap-3 p-4 ${live ? 'border-good/30' : ''}`}>
        {live ? <ImageIcon size={16} className="mt-0.5 shrink-0 text-good" /> : <Shapes size={16} className="mt-0.5 shrink-0 text-bone-faint" />}
        <div className="min-w-0">
          <div className={`font-mono text-[11px] uppercase tracking-[0.14em] ${live ? 'text-good' : 'text-signal'}`}>{image.label}</div>
          <p className="mt-1 font-sans text-[12px] font-light leading-relaxed text-bone-faint">
            {live
              ? `Scene images render on ${health?.image.provider} (${health?.image.model}) and are stored under company/episodes/${episode.id}/backgrounds/. Each clip scene gets its own keyframe — the image the video model animates.`
              : 'No image provider is configured (set REPLICATE_API_TOKEN for the media server). Scenes use procedural backdrops rendered from their shot specs — labelled as not AI-generated.'}
          </p>
        </div>
      </div>

      <p className="mt-3 font-mono text-[9.5px] uppercase tracking-[0.14em] text-bone-faint">
        {keyframes.length} clip keyframes · {backgrounds.length} backgrounds shared across {backgrounds.reduce((n, i) => n + i.sceneIds.length, 0)} scenes
      </p>

      <div className="mt-4 space-y-px">
        {plan.map((item) => (
          <AssetRow key={item.key} episode={episode} item={item} row={rows[item.key]} now={now} />
        ))}
      </div>

      <Btn className="mt-4" onClick={() => void run()} disabled={running}>
        <Play size={12} fill="currentColor" />
        {running ? 'rendering…' : finished ? 're-render visual assets' : 'generate visual assets'}
      </Btn>
    </div>
  )
}

/* ------------------------------------------------------------------- video */

export function VideoAssets({ episode, onChange }: { episode: Episode; onChange: (ep: Episode) => void }) {
  const { health } = useMediaStatus()
  const clips = useMemo(() => planEpisodeAssets(episode).filter((i) => i.kind === 'video'), [episode.id]) // eslint-disable-line react-hooks/exhaustive-deps
  const [rows, setRows] = useState<Record<string, Row>>({})
  const [running, setRunning] = useState(false)
  const now = useNow(running)
  const video = videoProvider()
  const live = video.tier === 'generated'
  const keyframeOf = (sceneId: string): AssetRef | undefined => episode.scenes[sceneId]?.assets?.background
  const missing = live ? clips.filter((c) => keyframeOf(c.sceneId)?.tier !== 'generated') : []

  async function run() {
    setRunning(true)
    let current = episode
    const set = (key: string, row: Row) => setRows((r) => ({ ...r, [key]: row }))
    await Promise.all(
      clips.map(async (item) => {
        const scene = current.scenes[item.sceneId]
        const image = scene.assets?.background
        if (live && image?.tier !== 'generated') return set(item.key, { status: 'blocked', note: 'generate visual assets first' })
        const startedAt = Date.now()
        set(item.key, { status: 'queued', startedAt })
        const job = await requestClip(scene.shot, { episodeId: current.id, sceneId: item.sceneId, image }, video)
        const done = await awaitClip(job, video, {
          intervalMs: 4000,
          timeoutMs: 8 * 60_000,
          onUpdate: (j) => (j.status === 'queued' || j.status === 'rendering') && set(item.key, { status: j.status, startedAt }),
        })
        const asset = clipToAsset(done)
        if (!asset) return set(item.key, { status: 'failed', note: done.error })
        current = attachAsset(current, item, asset)
        onChange(current)
        set(item.key, {
          status: asset.tier === 'generated' ? 'generated' : 'procedural',
          note: asset.storageKey ? `${asset.storageKey} · ${Math.round((Date.now() - startedAt) / 1000)}s` : undefined,
        })
      }),
    )
    setRunning(false)
  }

  const finished = clips.length > 0 && clips.every((i) => rows[i.key] && !['queued', 'rendering'].includes(rows[i.key].status))

  return (
    <div>
      <div className={`glass flex items-start gap-3 p-4 ${live ? 'border-good/30' : ''}`}>
        {live ? <Film size={16} className="mt-0.5 shrink-0 text-good" /> : <Shapes size={16} className="mt-0.5 shrink-0 text-bone-faint" />}
        <div className="min-w-0">
          <div className={`font-mono text-[11px] uppercase tracking-[0.14em] ${live ? 'text-good' : 'text-signal'}`}>
            {video.label}
            {live ? ' · image-to-video' : ''}
          </div>
          <p className="mt-1 font-sans text-[12px] font-light leading-relaxed text-bone-faint">
            {live
              ? `Each clip animates its scene keyframe on ${health?.video.provider} — about 5 seconds at 480p, rendered once and stored under company/episodes/${episode.id}/videos/. The model only animates the shot; the authored graph decides what happens.`
              : 'No video provider is configured (set REPLICATE_API_TOKEN for the media server). Every clip resolves to procedural previs rendered live from its shot spec — labelled that way in the player, never presented as AI video.'}
          </p>
        </div>
      </div>

      <p className="mt-3 font-mono text-[9.5px] uppercase tracking-[0.14em] text-bone-faint">
        {clips.length} clips (budget {DEFAULT_MAX_CLIPS}) · short cinematic shots, not a full video
      </p>
      {missing.length > 0 && (
        <p className="mt-2 font-mono text-[10px] text-signal">
          {missing.length} clip scene{missing.length === 1 ? '' : 's'} still need a generated keyframe — run visual assets first.
        </p>
      )}

      <div className="mt-4 space-y-px">
        {clips.map((item) => (
          <AssetRow key={item.key} episode={episode} item={item} row={rows[item.key]} now={now} detail={`${clipSeconds(episode.scenes[item.sceneId].shot)} s`} />
        ))}
      </div>

      <Btn className="mt-4" onClick={() => void run()} disabled={running || missing.length > 0}>
        <Film size={13} />
        {running ? 'rendering clips…' : finished ? 're-render cinematic video' : 'generate cinematic video'}
      </Btn>
    </div>
  )
}

/* ------------------------------------------------------------------- voice */

export function VoiceAssets({ episode, onChange }: { episode: Episode; onChange: (ep: Episode) => void }) {
  useMediaStatus()
  const lines = useMemo(() => planEpisodeAssets(episode).filter((i) => i.kind === 'audio'), [episode.id]) // eslint-disable-line react-hooks/exhaustive-deps
  const [rows, setRows] = useState<Record<string, Row>>({})
  const [running, setRunning] = useState(false)
  const provider = audioProvider()

  const byCharacter = useMemo(() => {
    const m = new Map<string, number>()
    for (const l of lines) m.set(l.characterId!, (m.get(l.characterId!) ?? 0) + 1)
    return [...m.entries()]
  }, [lines])

  async function run() {
    setRunning(true)
    let current = episode
    await pool(lines, 3, async (item) => {
      const scene = current.scenes[item.sceneId]
      const { asset, status, error } = await provider.renderLine({
        episodeId: current.id,
        sceneId: item.sceneId,
        lineIndex: item.lineIndex!,
        text: scene.dialogue[item.lineIndex!].line,
        character: getCharacter(item.characterId!),
      })
      if (asset) {
        current = attachAsset(current, item, asset)
        onChange(current)
      }
      setRows((r) => ({ ...r, [item.key]: { status: status === 'stored' ? 'generated' : status, note: error } }))
    })
    setRunning(false)
  }

  const counts = Object.values(rows).reduce<Record<string, number>>((acc, r) => ({ ...acc, [r.status]: (acc[r.status] ?? 0) + 1 }), {})

  return (
    <div>
      <div className="glass flex items-start gap-3 p-4">
        <Mic size={16} className={`mt-0.5 shrink-0 ${provider.id === 'elevenlabs' ? 'text-good' : 'text-bone-faint'}`} />
        <div>
          <div className={`font-mono text-[11px] uppercase tracking-[0.14em] ${provider.id === 'elevenlabs' ? 'text-good' : 'text-signal'}`}>
            {provider.label}
          </div>
          <p className="mt-1 font-sans text-[12px] font-light leading-relaxed text-bone-faint">
            {provider.id === 'elevenlabs'
              ? `Each line is voiced by its character's ElevenLabs voice through the voice proxy and stored under company/episodes/${episode.id}/audio/.`
              : 'No ElevenLabs key on the voice proxy, so nothing is pre-rendered. The player speaks lines with the browser voice at runtime, labelled BROWSER SYNTH. ElevenLabs is voice only — it does not generate video.'}
          </p>
        </div>
      </div>

      <div className="mt-4 grid gap-2 sm:grid-cols-2">
        {byCharacter.map(([id, n]) => {
          const ch = getCharacter(id)
          return (
            <div key={id} className="flex items-center gap-3 border border-bone/8 bg-ink-900/30 px-3 py-2">
              <span className="h-[12px] w-[2px]" style={{ background: ch.accent }} />
              <span className="font-mono text-[10px] uppercase tracking-[0.14em]" style={{ color: ch.accent }}>
                {ch.name}
              </span>
              <span className="min-w-0 flex-1 truncate font-mono text-[9px] text-bone-faint">
                {resolveVoiceProfile(ch.voiceProfileId).label.split(' — ')[0]}
              </span>
              <span className="font-mono text-[10px] tabular-nums text-bone-dim">{n} lines</span>
            </div>
          )
        })}
      </div>

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <Btn variant="outline" onClick={() => void run()} disabled={running}>
          <Mic size={12} />
          {running ? 'voicing…' : 'generate voice'}
        </Btn>
        <span className="font-mono text-[9.5px] uppercase tracking-[0.14em] text-bone-faint">
          {lines.length} character lines
          {Object.keys(counts).length > 0 &&
            ` · ${Object.entries(counts)
              .map(([k, v]) => `${v} ${STATUS_CHIP[k as RowStatus].label}`)
              .join(' · ')}`}
        </span>
      </div>
    </div>
  )
}
