import { Film, Image as ImageIcon, Mic, Play, Shapes } from 'lucide-react'
import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react'
import { characterGroups } from '@/content/characterGroups'
import { getCharacter } from '@/content/characters'
import { attachAsset, CLIPS_PER_SHOW, planEpisodeAssets, visualsFor, type AssetPlanItem } from '@/media/assetPlan'
import { audioProvider } from '@/media/audio'
import { imageProvider } from '@/media/image'
import { useMediaStatus } from '@/media/useMediaStatus'
import { awaitClip, clipSeconds, clipToAsset, requestClip, videoProvider } from '@/media/video'
import { resolveVoiceProfile } from '@/voice/voiceProfiles'
import type { Episode } from '@/types'
import { SceneCanvas } from '../SceneCanvas'
import { Btn, Chip } from '../ui/Bits'

/* ============================================================================
 * ASSET STUDIO — shot specs in, stored assets out, attached to the draft.
 *
 *   images  per show: backgrounds + one keyframe per clip scene, in its world
 *   video   per show: each keyframe animated into a ~5 s clip (image-to-video)
 *   voice   every character line of the episode's own cast
 *
 * Every show is its own universe, so images and clips are rendered once per
 * show, in one queue. Everything here happens before anyone plays. Each row
 * states the tier it actually got: generated by a model, or procedural previs.
 * ========================================================================== */

type RowStatus = 'queued' | 'rendering' | 'generated' | 'procedural' | 'runtime' | 'blocked' | 'failed'
export interface Row {
  status: RowStatus
  note?: string
  startedAt?: number
}

/**
 * The wizard mounts one step at a time, so a step's generation state can no
 * longer live in that step — navigating away would unmount it mid-render and
 * throw away every row's progress and elapsed timer while the async work kept
 * running underneath. The parent owns this instead, so the work simply keeps
 * writing into state that outlives the component that started it.
 */
export type AssetRun = { rows: Record<string, Row>; running: boolean }

const STATUS_CHIP: Record<RowStatus, { tone: 'good' | 'signal' | 'danger' | 'neutral' | 'cyan'; label: string }> = {
  queued: { tone: 'signal', label: 'queued' },
  rendering: { tone: 'signal', label: 'rendering…' },
  generated: { tone: 'good', label: 'ai generated · stored' },
  procedural: { tone: 'neutral', label: 'procedural previs' },
  runtime: { tone: 'neutral', label: 'runtime voice' },
  blocked: { tone: 'signal', label: 'needs scene image' },
  failed: { tone: 'danger', label: 'failed' },
}

function RowChip({ row, now }: { row?: Row; now: number }) {
  if (!row) return <Chip>waiting</Chip>
  const c = STATUS_CHIP[row.status]
  const live = (row.status === 'queued' || row.status === 'rendering') && row.startedAt
  return (
    <Chip tone={c.tone}>
      {c.label}
      {live ? ` ${Math.round((now - row.startedAt!) / 1000)}s` : ''}
    </Chip>
  )
}

/** Ticks while something is rendering, so elapsed times stay honest. */
function useNow(active: boolean) {
  const [now, setNow] = useState(Date.now())
  useEffect(() => {
    if (!active) return
    const t = setInterval(() => setNow(Date.now()), 1000)
    return () => clearInterval(t)
  }, [active])
  return now
}

async function pool<T>(items: T[], size: number, work: (item: T) => Promise<void>) {
  const queue = [...items]
  const worker = async () => {
    for (let item = queue.shift(); item !== undefined; item = queue.shift()) await work(item)
  }
  await Promise.all(Array.from({ length: Math.min(size, items.length) }, worker))
}

const settled = (row?: Row) => !!row && row.status !== 'queued' && row.status !== 'rendering'

/** Every show's plan for one asset kind, show by show — the order they render in. */
const planAllShows = (episode: Episode, kind: 'image' | 'video') =>
  characterGroups.flatMap((g) => planEpisodeAssets(episode, { groupId: g.id }).filter((i) => i.kind === kind))

function AssetRow({ episode, item, row, now, detail }: { episode: Episode; item: AssetPlanItem; row?: Row; now: number; detail?: string }) {
  const scene = episode.scenes[item.sceneId]
  const visuals = visualsFor(episode, item.sceneId, item.groupId)
  return (
    <div className="flex items-center gap-3 rounded border border-bone/8 bg-ink-900/30 p-2.5" data-asset-row={item.key}>
      <div className="relative aspect-video w-28 shrink-0 overflow-hidden rounded border border-bone/10 sm:w-40">
        <SceneCanvas shot={scene.shot} sceneKey={`thumb-${item.key}`} paused assets={item.kind === 'image' ? { background: visuals?.background } : visuals} />
      </div>
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-2">
          <span className="font-mono text-[9px] uppercase tracking-[0.14em] text-signal">
            {item.kind === 'video' ? 'clip' : item.keyframe ? 'keyframe' : 'background'}
          </span>
          <span className="truncate font-sans text-[12.5px] text-bone">{scene.title ?? scene.outcome?.banner ?? scene.id}</span>
          <span className="font-mono text-[9px] text-bone-faint">
            {item.reason}
            {item.sceneIds.length > 1 ? ` · ×${item.sceneIds.length} scenes` : ''}
            {detail ? ` · ${detail}` : ''}
          </span>
        </div>
        <p className="mt-1 line-clamp-2 font-sans text-[11px] font-light leading-snug text-bone-faint">{item.prompt}</p>
        {row?.note && <p className="mt-0.5 truncate font-mono text-[9px] text-bone-faint">{row.note}</p>}
      </div>
      <RowChip row={row} now={now} />
    </div>
  )
}

/** One tab per show, each with its own progress. The queue renders all of them. */
function ShowTabs({ active, onPick, progress }: { active: string; onPick: (id: string) => void; progress: (id: string) => string }) {
  return (
    <div className="mt-4 flex flex-wrap gap-2" role="tablist" aria-label="Show">
      {characterGroups.map((g) => (
        <button
          key={g.id}
          role="tab"
          aria-selected={active === g.id}
          onClick={() => onPick(g.id)}
          className={`rounded border px-3 py-2 text-left transition-colors ${
            active === g.id ? 'border-signal/70 bg-signal/[0.07]' : 'border-bone/12 hover:border-bone/35'
          }`}
        >
          <span className="block font-mono text-[10px] uppercase tracking-[0.14em] text-bone">{g.name}</span>
          <span className="block font-mono text-[9px] tabular-nums text-bone-faint">{progress(g.id)}</span>
        </button>
      ))}
    </div>
  )
}

/* ------------------------------------------------------------------ images */

export function VisualAssets({
  episode,
  onChange,
  run: runState,
  setRun,
}: {
  episode: Episode
  onChange: (ep: Episode) => void
  run: AssetRun
  setRun: Dispatch<SetStateAction<AssetRun>>
}) {
  const { health } = useMediaStatus()
  const plan = useMemo(() => planAllShows(episode, 'image'), [episode.id]) // eslint-disable-line react-hooks/exhaustive-deps
  const [show, setShow] = useState(episode.groupId)
  const rows = runState.rows
  const running = runState.running
  const now = useNow(running)
  const image = imageProvider()
  const live = image.tier === 'generated'
  const shown = plan.filter((i) => i.groupId === show)
  const keyframes = shown.filter((i) => i.keyframe)
  const characterStills = !!health?.image.characters
  const showName = characterGroups.find((g) => g.id === show)?.name ?? show

  /**
   * Stills already in storage are reused; `force` (re-render) generates them
   * again. `only` renders one show — a cheap way to judge the look first.
   */
  async function run(force: boolean, only?: string) {
    setRun((r) => ({ ...r, running: true }))
    let current = episode
    const set = (key: string, row: Row) => setRun((r) => ({ ...r, rows: { ...r.rows, [key]: row } }))
    await pool(only ? plan.filter((i) => i.groupId === only) : plan, 4, async (item) => {
      set(item.key, { status: 'rendering', startedAt: Date.now() })
      // Without a model that takes character references, a still is the setting alone.
      const withCast = characterStills && !!item.characters?.length
      const request = { episodeId: current.id, sceneId: item.sceneId, force, showId: item.groupId }
      let result = await image.generateBackground({ ...request, prompt: withCast ? item.prompt : (item.fallbackPrompt ?? item.prompt), references: withCast ? item.characters : undefined })
      let drawn = withCast ? item.characters : undefined
      let detail = drawn ? ` · ${drawn.map((c) => getCharacter(c).name.split(' ')[0]).join(', ')}` : ''
      if (result.refused && withCast) {
        // Declined with the cast: the setting alone, under its own key, with portraits on top as before.
        result = await image.generateBackground({ ...request, sceneId: `${item.sceneId}-setting`, prompt: item.fallbackPrompt ?? item.prompt })
        drawn = undefined
        detail = ' · model declined the characters — setting only'
      }
      const { asset, error, reused } = result
      if (!asset) return set(item.key, { status: 'failed', note: error })
      current = attachAsset(current, item, { ...asset, characters: asset.characters ?? drawn })
      onChange(current)
      set(item.key, {
        status: asset.tier === 'generated' ? 'generated' : 'procedural',
        note: asset.storageKey && `${asset.storageKey}${detail}${reused ? ' · reused from storage' : ''}`,
      })
    })
    setRun((r) => ({ ...r, running: false }))
  }

  const finished = plan.length > 0 && plan.every((i) => settled(rows[i.key]))
  const progress = (id: string) => {
    const of = plan.filter((i) => i.groupId === id)
    return `${of.filter((i) => visualsFor(episode, i.sceneId, id)?.background).length}/${of.length} stills`
  }

  return (
    <div>
      <div className={`glass flex items-start gap-3 p-4 ${live ? 'border-good/30' : ''}`}>
        {live ? <ImageIcon size={16} className="mt-0.5 shrink-0 text-good" /> : <Shapes size={16} className="mt-0.5 shrink-0 text-bone-faint" />}
        <div className="min-w-0">
          <div className={`font-mono text-[11px] uppercase tracking-[0.14em] ${live ? 'text-good' : 'text-signal'}`}>{image.label}</div>
          <p className="mt-1 font-sans text-[12px] font-light leading-relaxed text-bone-faint">
            {live
              ? characterStills
                ? `Every scene gets a still in each show's world, drawn by ${health?.image.provider} (${health?.image.model}) with the characters who speak in it — their portraits go in as references. Stored under company/episodes/${episode.id}/<show>/backgrounds/. If the model declines to draw the characters, that still falls back to the setting with the portrait on top.`
                : `Every scene gets a still of its setting in each show's world, rendered on ${health?.image.provider} (${health?.image.model}) and stored under company/episodes/${episode.id}/<show>/backgrounds/. This model takes no character references, so the cast appears as portraits on top.`
              : 'No image provider is configured (set REPLICATE_API_TOKEN for the media server). Scenes use procedural backdrops rendered from their shot specs — labelled as not AI-generated.'}
          </p>
        </div>
      </div>

      <ShowTabs active={show} onPick={setShow} progress={progress} />

      <p className="mt-3 font-mono text-[9.5px] uppercase tracking-[0.14em] text-bone-faint">
        {shown.length} stills · {shown.filter((i) => i.characters?.length).length} with the cast · {keyframes.length} animated ·{' '}
        {plan.length} stills across {characterGroups.length} shows
      </p>

      <div className="mt-4 space-y-px">
        {shown.map((item) => (
          <AssetRow key={item.key} episode={episode} item={item} row={rows[item.key]} now={now} />
        ))}
      </div>

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <Btn onClick={() => void run(finished)} disabled={running}>
          <Play size={12} fill="currentColor" />
          {running ? 'rendering…' : finished ? 're-render visual assets' : 'generate visual assets'}
        </Btn>
        <Btn variant="outline" onClick={() => void run(false, show)} disabled={running}>
          <Play size={12} /> render {showName} only
        </Btn>
      </div>
    </div>
  )
}

/* ------------------------------------------------------------------- video */

export function VideoAssets({
  episode,
  onChange,
  run: runState,
  setRun,
}: {
  episode: Episode
  onChange: (ep: Episode) => void
  run: AssetRun
  setRun: Dispatch<SetStateAction<AssetRun>>
}) {
  const { health } = useMediaStatus()
  const clips = useMemo(() => planAllShows(episode, 'video'), [episode.id]) // eslint-disable-line react-hooks/exhaustive-deps
  const [show, setShow] = useState(episode.groupId)
  const rows = runState.rows
  const running = runState.running
  const now = useNow(running)
  const video = videoProvider()
  const live = video.tier === 'generated'
  const keyframeOf = (item: AssetPlanItem, ep: Episode = episode) => visualsFor(ep, item.sceneId, item.groupId)?.background
  const missing = live ? clips.filter((c) => keyframeOf(c)?.tier !== 'generated') : []
  const shown = clips.filter((i) => i.groupId === show)

  const showName = characterGroups.find((g) => g.id === show)?.name ?? show

  /** Clips already in storage are reused; `force` (re-render) pays for new predictions. `only` renders one show. */
  async function run(force: boolean, only?: string) {
    setRun((r) => ({ ...r, running: true }))
    let current = episode
    const set = (key: string, row: Row) => setRun((r) => ({ ...r, rows: { ...r.rows, [key]: row } }))
    await Promise.all(
      (only ? clips.filter((i) => i.groupId === only) : clips).map(async (item) => {
        const scene = current.scenes[item.sceneId]
        const image = keyframeOf(item, current)
        if (live && image?.tier !== 'generated') return set(item.key, { status: 'blocked', note: 'generate visual assets first' })
        const startedAt = Date.now()
        set(item.key, { status: 'queued', startedAt })
        const job = await requestClip(
          scene.shot,
          { episodeId: current.id, sceneId: item.sceneId, image, force, showId: item.groupId, opening: item.sceneId === current.entrySceneId },
          video,
        )
        const done = await awaitClip(job, video, {
          intervalMs: 4000,
          timeoutMs: 12 * 60_000,
          onUpdate: (j) => (j.status === 'queued' || j.status === 'rendering') && set(item.key, { status: j.status, startedAt }),
        })
        const asset = clipToAsset(done)
        if (!asset) return set(item.key, { status: 'failed', note: done.error })
        current = attachAsset(current, item, asset)
        onChange(current)
        set(item.key, {
          status: asset.tier === 'generated' ? 'generated' : 'procedural',
          note: asset.storageKey
            ? `${asset.storageKey} · ${done.reused ? 'reused from storage' : `${Math.round((Date.now() - startedAt) / 1000)}s`}`
            : undefined,
        })
      }),
    )
    setRun((r) => ({ ...r, running: false }))
  }

  const finished = clips.length > 0 && clips.every((i) => settled(rows[i.key]))
  const progress = (id: string) => {
    const of = clips.filter((i) => i.groupId === id)
    return `${of.filter((i) => visualsFor(episode, i.sceneId, id)?.video).length}/${of.length} clips`
  }

  return (
    <div>
      <div className={`glass flex items-start gap-3 p-4 ${live ? 'border-good/30' : ''}`}>
        {live ? <Film size={16} className="mt-0.5 shrink-0 text-good" /> : <Shapes size={16} className="mt-0.5 shrink-0 text-bone-faint" />}
        <div className="min-w-0">
          <div className={`font-mono text-[11px] uppercase tracking-[0.14em] ${live ? 'text-good' : 'text-signal'}`}>
            {video.label}
            {live ? ' · image-to-video' : ''}
          </div>
          <p className="mt-1 font-sans text-[12px] font-light leading-relaxed text-bone-faint">
            {live
              ? `Every show gets ${CLIPS_PER_SHOW} clips — its cold open and its incident — each animating that show's still on ${health?.video.provider} —about 5 seconds at 480p, stored under company/episodes/${episode.id}/<show>/videos/ (a clip already in storage is reused; re-render pays for a new one). The model only animates the shot; the authored graph decides what happens.`
              : 'No video provider is configured (set REPLICATE_API_TOKEN for the media server). Every clip resolves to procedural previs rendered live from its shot spec — labelled that way in the player, never presented as AI video.'}
          </p>
        </div>
      </div>

      <ShowTabs active={show} onPick={setShow} progress={progress} />

      <p className="mt-3 font-mono text-[9.5px] uppercase tracking-[0.14em] text-bone-faint">
        {shown.length} clips per show — the cold open and the incident · {clips.length} across {characterGroups.length} shows · every other scene is a still
      </p>
      {missing.length > 0 && (
        <p className="mt-2 font-mono text-[10px] text-signal">
          {missing.length} clip{missing.length === 1 ? '' : 's'} still need their still — those are skipped until visual assets finish.
        </p>
      )}

      <div className="mt-4 space-y-px">
        {shown.map((item) => (
          <AssetRow key={item.key} episode={episode} item={item} row={rows[item.key]} now={now} detail={`${clipSeconds(episode.scenes[item.sceneId].shot)} s`} />
        ))}
      </div>

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <Btn onClick={() => void run(finished)} disabled={running || (live && missing.length === clips.length)}>
          <Film size={13} />
          {running ? 'rendering clips…' : finished ? 're-render cinematic video' : 'generate cinematic video'}
        </Btn>
        <Btn variant="outline" onClick={() => void run(false, show)} disabled={running}>
          <Film size={12} /> render {showName} only
        </Btn>
      </div>
    </div>
  )
}

/* ------------------------------------------------------------------- voice */

export function VoiceAssets({
  episode,
  onChange,
  run: runState,
  setRun,
}: {
  episode: Episode
  onChange: (ep: Episode) => void
  run: AssetRun
  setRun: Dispatch<SetStateAction<AssetRun>>
}) {
  useMediaStatus()
  const lines = useMemo(() => planEpisodeAssets(episode).filter((i) => i.kind === 'audio'), [episode.id]) // eslint-disable-line react-hooks/exhaustive-deps
  const rows = runState.rows
  const running = runState.running
  const provider = audioProvider()

  const byCharacter = useMemo(() => {
    const m = new Map<string, number>()
    for (const l of lines) m.set(l.characterId!, (m.get(l.characterId!) ?? 0) + 1)
    return [...m.entries()]
  }, [lines])

  async function run() {
    setRun((r) => ({ ...r, running: true }))
    let current = episode
    await pool(lines, 3, async (item) => {
      const scene = current.scenes[item.sceneId]
      const { asset, status, error } = await provider.renderLine({
        episodeId: current.id,
        sceneId: item.sceneId,
        lineIndex: item.lineIndex!,
        text: scene.dialogue[item.lineIndex!].line,
        character: getCharacter(item.characterId!),
      })
      if (asset) {
        current = attachAsset(current, item, asset)
        onChange(current)
      }
      setRun((r) => ({ ...r, rows: { ...r.rows, [item.key]: { status: status === 'stored' ? 'generated' : status, note: error } } }))
    })
    setRun((r) => ({ ...r, running: false }))
  }

  const counts = Object.values(rows).reduce<Record<string, number>>((acc, r) => ({ ...acc, [r.status]: (acc[r.status] ?? 0) + 1 }), {})

  return (
    <div>
      <div className="glass flex items-start gap-3 p-4">
        <Mic size={16} className={`mt-0.5 shrink-0 ${provider.id === 'elevenlabs' ? 'text-good' : 'text-bone-faint'}`} />
        <div>
          <div className={`font-mono text-[11px] uppercase tracking-[0.14em] ${provider.id === 'elevenlabs' ? 'text-good' : 'text-signal'}`}>
            {provider.label}
          </div>
          <p className="mt-1 font-sans text-[12px] font-light leading-relaxed text-bone-faint">
            {provider.id === 'elevenlabs'
              ? `Each line is voiced by its character's ElevenLabs voice through the voice proxy and stored under company/episodes/${episode.id}/audio/.`
              : 'No ElevenLabs key on the voice proxy, so nothing is pre-rendered. The player speaks lines with the browser voice at runtime, labelled BROWSER SYNTH. ElevenLabs is voice only — it does not generate video.'}
          </p>
        </div>
      </div>

      <div className="mt-4 grid gap-2 sm:grid-cols-2">
        {byCharacter.map(([id, n]) => {
          const ch = getCharacter(id)
          return (
            <div key={id} className="flex items-center gap-3 rounded border border-bone/8 bg-ink-900/30 px-3 py-2">
              <span className="h-[12px] w-[2px]" style={{ background: ch.accent }} />
              <span className="font-mono text-[10px] uppercase tracking-[0.14em]" style={{ color: ch.accent }}>
                {ch.name}
              </span>
              <span className="min-w-0 flex-1 truncate font-mono text-[9px] text-bone-faint">
                {resolveVoiceProfile(ch.voiceProfileId).label.split(' — ')[0]}
              </span>
              <span className="font-mono text-[10px] tabular-nums text-bone-dim">{n} lines</span>
            </div>
          )
        })}
      </div>

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <Btn variant="outline" onClick={() => void run()} disabled={running}>
          <Mic size={12} />
          {running ? 'voicing…' : 'generate voice'}
        </Btn>
        <span className="font-mono text-[9.5px] uppercase tracking-[0.14em] text-bone-faint">
          {lines.length} character lines
          {Object.keys(counts).length > 0 &&
            ` · ${Object.entries(counts)
              .map(([k, v]) => `${v} ${STATUS_CHIP[k as RowStatus].label}`)
              .join(' · ')}`}
        </span>
      </div>
    </div>
  )
}
